### ISSUE TITLE
Unable to open to signalen.s-hertogenbosch.dev/ on iPhone

### ISSUE THREAD

**Issue by erikveerm** [Signalen/backend#28] opened 2020-06-04 07:44 UTC
I'm unable to open the webform on my mobile device (iPhone) when I try to open the webform the second time. The first it works as it should, the second time I get a blank page.
 
When I remove the history and website data in Safari I can open the webform again. All colleague's at Den Bosch get an iPhone managed by out ICT dept. It's possible this is a problem within our network/settings. But I'm unable to test this due to a lack of a personal iPhone. 

On a Android device (not managed by Den Bosch) this problem doesn't occur.

**Comment by bartjkdp** [comment] 2020-06-18 09:45
Duplicate of #29

**Closed by bartjkdp** 2020-06-18 09:45 UTC
